version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
